# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "inventory-admin"
client_id = "29f6f2601b2ab8c7549aaa6d6654dba4"
application_url = "https://blah-apparatus-retrieval-aids.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://blah-apparatus-retrieval-aids.trycloudflare.com/auth/callback",
  "https://blah-apparatus-retrieval-aids.trycloudflare.com/auth/shopify/callback",
  "https://blah-apparatus-retrieval-aids.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-1954a5ae.myshopify.com"
